name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  es-lint:
    name: ESLint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint . --ext .js,.jsx,.ts,.tsx
  build:
    needs: [ es-lint ]
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: npx next build

  Tests:
    needs: [ build ]
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Built test enviroment
        run: npm install
      - name: Test
        run: npm test

  docker:
    name: Dev docker build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker-compose up -d